### ISSUE TITLE
Tune PID controller for UR5 Gazebo

### ISSUE THREAD

**Issue by iibrahimli** [UHHRobotics22-23/marimbabot#103]
Right now the arm controllers are unstable / have steady state error. PID values need tuning (in file `marimbabot_ur5_moveit_config/config/arm_controller_ur5.yaml`)

**Comment by iibrahimli** [comment]
TODO: Norman suggested that we should try just adding the mallet to his setup (`tams_ur5_gazebo`) and see if the default PID values work in that case

**Comment by iibrahimli** [comment]
UPD: The default PID values cause shaking for smaller movements (e.g. move pan by 0.1 rad) while being stable for long-range movements (e.g. from one predefined position to another). Thanks @normanhendrich for testing this with default UR5 setup.

Sensible next step is to test the motion planning scripts in Gazebo and tune the PID values based on that. I will get on that as soon as #80 is merged.

**Comment by Juphex** [comment]
What is the current status?
@ateRstones  and I wondered

**Comment by Flova** [comment]
I think they were tuned some time ago. If there are still issues open another ticket.
