### ISSUE TITLE
Clean up marimbabot_ur5_moveit_config package

### ISSUE THREAD

**Issue by iibrahimli** [UHHRobotics22-23/marimbabot#105]
We have a lot of config/launch files. We suspect that some of them are not included anywhere and are not relevant for the project in foreseeable future. Removing them will clean up the project structure.

**Comment by Juphex** [comment]
You mean all the files in marimbabot_ur5_moveit_config, right @iibrahimli ?

**Comment by iibrahimli** [comment]
> You mean all the files in marimbabot_ur5_moveit_config, right @iibrahimli ?
> 
> 

yes
