### ISSUE TITLE
Integrate the two mallet control for the full planning and test it

### ISSUE THREAD

**Issue by ateRstones** [UHHRobotics22-23/marimbabot#130]

**Comment by Juphex** [comment]
Have you tried the planning part already? :)
I have spent couple hours today but have not moved forward regarding two mellots. Maybe I was missing something

**Comment by ateRstones** [comment]
I have been more involved in actually being able to control it with everything, the planning is afaik WIP

**Comment by ateRstones** [comment]
I consider this closed as the two mallet control is controllable by our planning
