### ISSUE TITLE
Make sides of marimba model smaller

### ISSUE THREAD

**Issue by iibrahimli** [UHHRobotics22-23/marimbabot#131]
Side boxes are too high and interfere with motion for edge bars

**Comment by Juphex** [comment]
I have seen that you have many open issues. If you have a high workload at the moment, I wanted to offer my assistance if possible. :) 
E.g. I could take this issue

**Comment by iibrahimli** [comment]
> @iibrahimli I have seen that you have many open issues. If you have a high workload at the moment, I wanted to offer my assistance if possible. :) 
> E.g. I could take this issue

Appreciate it. You can take this ticket if you have extra time, thanks.
