### ISSUE TITLE
lilypond_to_audio - behavior integration

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#150]
create topic for lilypond_to_audio (message is lilypond string)  

or create an action (for feedback)

**Comment by Juphex** [comment]
lilypond_to_audio already has a subscription on a topic. (Used outgoing from the vision network)
I will rename the topic that is subscribes to :)

**Comment by Juphex** [comment]
There is already a subscribtion on a topic. 
However, the name is 'vision_node/recognized_notes'. Maybe it makes sense to create a second topic just exactly for the behavior part.

**Comment by Flova** [comment]
The `vision_node/recognized_notes` is the vision output right? I think this issue was describing the `behavior -> midi synth` communication.

**Comment by Juphex** [comment]
@Flova 
You are right. The audio not was just subscribing on it by default.
