### ISSUE TITLE
Fix URDF and moveit config regarding Flos feedback

### ISSUE THREAD

**Issue by ateRstones** [UHHRobotics22-23/marimbabot#165]
https://github.com/UHHRobotics22-23/marimbabot/tree/fix/flex_double_srdf

**Comment by Juphex** [comment]
@Flova @ateRstones 
what is the current status?

**Comment by Flova** [comment]
Idk what this issue is about tbh. At some point I criticized some issues with the double mallet urdf and internal collisions in it. I also noticed that the collision exceptions in the srdf were inconsistent (some notes where missing, only one mallet etc.).

**Comment by ateRstones** [comment]
Ok, I see. I'll go through the config and recheck it when I have time. We used the automatic generation of the collision matrix and then removed some stuff. Probably something was missed randomly and were not careful enough in removing unwanted collisions

**Comment by ateRstones** [comment]
Closed as of pr #219
