### ISSUE TITLE
handle command detection during tts (or in complex/ loud environments)

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#167]
maybe make use of the topic /behavior_node/response

**Comment by scaredycode** [comment]
It's basically how to handle voice recognition while the speech synthesis is actively producing speech or when people are speaking in the background. Yunlong said the command detection is very sensitive so this ticket is just a reminder to think about solutions in situations like this.
I think the keyword "Marimbabot" works fine but the command detection also needs 2s of silence to signal the end of a command, which might not always be possible in every situation.
So far no testing was performed and we might need to consider adjusting the detection sensitivity or applying some sort of noise filter.

And no, I'm not working on this. I opened the ticket for yunlong some time ago when I talked to him about it and he asked me to make a ticket.

**Comment by Juphex** [comment]
Thank you for the elaboration on this. :)

**Comment by yunlong-wang-cn** [comment]
I think it can be solved by adding [keyword spotting](https://github.com/zycv/awesome-keyword-spotting.git), which can extract text from speech when the keyword is spotted. And at the exhibition, the audience could focus on what you are doing, there could be not so much noise.

**Comment by yunlong-wang-cn** [comment]
done in #230 by using hot word spotting, then close it.
