### ISSUE TITLE
Incorperate the audio feedback into the planning evaluation and potential recalibration

### ISSUE THREAD

**Issue by ateRstones** [UHHRobotics22-23/marimbabot#173]

**Comment by Juphex** [comment]
@scaredycode  @yunlong-wang-cn is that something you are currently doing?

**Comment by scaredycode** [comment]
I think so far the Audio feedback only assigns one final score for the whole performance, which might not be enough for a fall recalibration. But @yunlong-wang-cn should probably be able to elaborate further.

**Comment by yunlong-wang-cn** [comment]
@Juphex  In your opinion which part of the planning should be optimized? or recalibrated?  I don't know much about the details of motion planning, perhaps I need a brief introduction.

**Comment by ateRstones** [comment]
We could use the audio feedback to detect when we missplayed and then use the information to adjust our world model of the marimba. But maybe this is not needed and a simple score suffices for us

**Comment by yunlong-wang-cn** [comment]
> We could use the audio feedback to detect when we missplayed and then use the information to adjust our world model of the marimba. But maybe this is not needed and a simple score suffices for us

@ateRstones The mismatched note and final score(recall) is available now from this issue #201, just haven't been merged into the main branch. I will create a PR when I am done with its visualization.

**Comment by Juphex** [comment]
can we close this @Flova ?

**Comment by Juphex** [comment]
I close this. Due to no interactions and probably out of our scope.
