### ISSUE TITLE
communicate (exact) time of the first bar hit (for audio feedback)

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#179]
audio feedback needs to know the time of the first hit for audio comparison.
Maybe there is a way, the this information can be forwarded after the planning is finished and the motion starts?

actual time of first hit = time of received message + planning duration (+ delay between planning and motions start) + duration of motion to first bar

OR

forward the whole trajectory of planning (exact timings per note)
-> if planning fails to comply with the timings in the goal sequence, audio feedback can still work with the plan

**Comment by Juphex** [comment]
TODO @Juphex 
forward the information from behaviour to audio topic "/audio/hit_sequence" in node [marimbabot_audio/scripts/score.py](https://github.com/UHHRobotics22-23/marimbabot/blob/9ad03b69eb7f8fda2e53f07c869245adf038c8c2/marimbabot_audio/scripts/score.py#L22)
