### ISSUE TITLE
Refactor marimbabot_bringup launch files 

### ISSUE THREAD

**Issue by Juphex** [UHHRobotics22-23/marimbabot#196]
E.g. combine all launch files

**Comment by Flova** [comment]
What do you mean by combine all launch files?

**Comment by Juphex** [comment]
@Flova 
I am not quite sure what the state of the launch files were.
But they seem to be fine, except maybe we add some documentation

**Comment by Flova** [comment]
Does the main lauch file launch everything?

**Comment by Flova** [comment]
It seems so in yesterdays tests
