### ISSUE TITLE
Report Paper for End of Project with annotated parts. 6-10+ pages IEEE conference style

### ISSUE THREAD

**Issue by ateRstones** [UHHRobotics22-23/MarimbaBot#207]
The requirements is [here](https://tams.informatik.uni-hamburg.de/lectures/2022ws/projekt/irMSc/):

At the end of the project, the group has to document their efforts. This work is split in two parts.

First, all final **source code and project structure** that was developed during the project **should be documented**. The aim of this part is to enable a person with no affiliations to the project to run and develop on top of the final demonstration. Useful documentation includes a technical overview of each part (usually **in the form of a README.md** for each component) with sufficient instructions to start and develop the demonstration scenario. If there are **known issues** that can break demonstrations, these should be documented as well. Lastly, the actual source **code should be sufficiently structured and commented** to be accessible later on.

Second, all abstract aspects of the project should be summarized in a **written document** [in the **style of an IEEE** conference publication](http://ras.papercept.net/conferences/support/tex.php). These aspects comprise everything you would expect to see in a scientific publication while abstracting **away implementation details** (which are documented in the first part).

- Overall scope and structure of the developed system
- Related work of the system and the individual components
- Methods and considered alternatives for implemented components
- Limitations of the chosen approaches
- If experiments were performed, a conclusive evaluation of the observed effects.

**Comment by ateRstones** [comment]
I stated a overleaf for this https://www.overleaf.com/4848141235rnjsgbtmbhnt
We could also use git, but this I think is a bit more involved than our expose so I would expect more conflicts possibly

**Comment by cvhex** [comment]
https://docs.google.com/presentation/d/1Oi_m2aNIBA3nVfwhzWw8N8VOkm-Lhm6JC1UM5gr76Yg/edit?usp=sharing

**Comment by Flova** [comment]
It is submitted!
