### ISSUE TITLE
Create Rosbags for Integrated or Semiintegrated environments of the project to be used for testing nodes in a isolated state

### ISSUE THREAD

**Issue by ateRstones** [UHHRobotics22-23/marimbabot#213]

**Comment by yunlong-wang-cn** [comment]
I will try to create two rosbag:
1. to collect the audio information from the robot playing with the single mallet, here I need help from @Flova or @berkgungor on how to use the robot, I need to know the interface, if you have it done please let me know.
2. to collect some human speech under common situations (i.e. with some noise and/or robots speaking) to test/calibrate the robustness of the speech recognition.

**Comment by Juphex** [comment]
Can you give an update?
@yunlong-wang-cn
