### ISSUE TITLE
inconsistency in handwritten detections

### ISSUE THREAD

**Issue by berkgungor** [UHHRobotics22-23/marimbabot#234]
- Hand written tempo and loudness values (tempo=120 , fff, pp) have considerable consistency.
- Recognition of magnetic notes is good but has a little inconsistency.

**Comment by berkgungor** [comment]
![Screenshot_2023-08-17_13-41-18](https://github.com/UHHRobotics22-23/marimbabot/assets/48314701/6e75ad47-433e-4374-a7a5-1eac27388c28)

**Comment by Juphex** [comment]
related to 
https://github.com/UHHRobotics22-23/marimbabot/issues/43
https://github.com/UHHRobotics22-23/marimbabot/issues/66

**Comment by Flova** [comment]
As they are in the beginning of the sequence we can also collect data only featuring tempo information, but no notes. This should be way faster to collect.

**Comment by Flova** [comment]
The same procedure is possible for keys etc

**Comment by Juphex** [comment]
What is the status of major/minor keys + bpm collection from last week @cvhex ?

**Comment by Juphex** [comment]
Can we close this @Flova ?
