### ISSUE TITLE
inconsistency in planning - finding an valid plan

### ISSUE THREAD

**Issue by berkgungor** [UHHRobotics22-23/marimbabot#239]
- valid plan could not be found right after the same plan was generated.

**Comment by berkgungor** [comment]
Issue happened when I tried to make play the notes slower.
(motion was generated for Tempo=120, not for 100 )

**Comment by Flova** [comment]
It could be related to the interpolation. We should have a look at the generated trajectories in rqt and plotjuggler (?)

**Comment by Juphex** [comment]
Can we close this @Flova

**Comment by Flova** [comment]
It is way more consistent now, so I would think so.
