### ISSUE TITLE
Loudness limitation in marimbabor_behaviour

### ISSUE THREAD

**Issue by berkgungor** [UHHRobotics22-23/marimbabot#258]
When we try to decrease loudness level, robot performs well and hits slower to the bars.
However, when we tried to increase loudness level all the way, robot does not increase loudness as its maximum.

Possible reason : in interpreter.py, note.velocity is devided by 127 regardless. and that result is passed into hitsequenceelement to perform planning.

- in prettyMIDI library, notes have a velocity (volume) from 1 to 127, from quietest to loudest. In that case we need to investigate this constant division.

**Comment by Juphex** [comment]
Haven't had time to investigate yet

**Comment by berkgungor** [comment]
code was modified and tested, issue fixed. See #242
