### ISSUE TITLE
add documentation on planning node

### ISSUE THREAD

**Issue by Juphex** [UHHRobotics22-23/MarimbaBot#263]
Please, someone document how to use scripts and test/run the planning node.
Preferably in the README of the package. This also helps others how to use this package.
This may include changing the "main" README.
These steps are needed:

roslaunch marimbabot_ur5_flex_double_moveit_config demo.launch 
rosrun marimbabot_planning planning 

and running any of the scripts, e.g.:
rosrun marimbabot_planning sound_pad.py

**Comment by Flova** [comment]
Please use the launch file and not `rosrun` if one is present as it might perform additional things like parameter loading

**Comment by berkgungor** [comment]
how we are gonna make specifically py files run without using `rosrun` ?

**Comment by Flova** [comment]
What do you mean? `rosrun` is a valid option no launch file exists.

**Comment by berkgungor** [comment]
what did you mean while saying "Please use the launch file and not rosrun" ?, bcs i added rosrun commands for .py files into the planning documentation.

**Comment by Flova** [comment]
This text of this issue states:

> roslaunch marimbabot_ur5_flex_double_moveit_config demo.launch
rosrun marimbabot_planning planning

Which should be

>roslaunch marimbabot_ur5_flex_double_moveit_config demo.launch
roslaunch marimbabot_planning marimbabot.launch

**Comment by Flova** [comment]
Done
