### ISSUE TITLE
Collect extended data set

### ISSUE THREAD

**Issue by Juphex** [UHHRobotics22-23/MarimbaBot#43]
add accidentals, different note durations, 'dotted' notes ... 

dataset storage: https://cloud.mafiasi.de/f/17816624

data collection script: https://github.com/UHHRobotics22-23/marimbabot/blob/main/marimbabot_vision/scripts/real_world_data_collection.py

**Comment by Juphex** [comment]
I would like to tackle this task this week. Can anyone join me? @ateRstones @Flova @iibrahimli  @cvhex @yunlong-wang-cn @berkgungor @scaredycode

**Comment by Flova** [comment]
I will keep working on the motion side of things, but feel free come to me if you have any additional questions.

**Comment by yunlong-wang-cn** [comment]
@Juphex  Even though I also have some stuff to do, I will join you.

**Comment by Juphex** [comment]
I had to add slurs, accidentals and dynamics to the data set first. We, or other people, could do it next week @yunlong-wang-cn :)

**Comment by yunlong-wang-cn** [comment]
when you need help, just let me know. @Juphex

**Comment by Juphex** [comment]
@Flova 
Since this is a time-exhaustive task and we still have (https://github.com/UHHRobotics22-23/marimbabot/issues/42) open : somewhat like 30 samples should be enough, right?

**Comment by Juphex** [comment]
@Flova  we have 16 samples now. Would you like to try it with 16 real-life samples right now? I mean we can apply data augmentation on them 😅

**Comment by Juphex** [comment]
As discussed today in our meeting,
the real dife data collection is on hold and waits for the results of training on handwritten data generation by @scaredycode .
