### ISSUE TITLE
Speed up or slow down trajectories to match rythm

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#49]

**Comment by ateRstones** [comment]
I see this and #61 are connected to the closed pull request #118 . Are these obsolete tickets @berkgungor ?

**Comment by Juphex** [comment]
@ateRstones https://github.com/UHHRobotics22-23/marimbabot/issues/61 is already tackeled. I assume that here it is about changing the speed according to a user input?

**Comment by berkgungor** [comment]
#61 was an old ticket and related to #118 pull request as @ateRstones mentioned and I just closed the ticket #61.  I am also closing this ticket too as it addresses the same issue.
