### ISSUE TITLE
Hit note with end of mallet and additional constrains (bio_ik)

### ISSUE THREAD

**Issue by Flova** [UHHRobotics22-23/marimbabot#60]
We currently only rotate the wrist in a fixed way, but if we incorporate the marimba model in our planning pipeline we need to specify the hit point via the end of the mallet and not via the wrist pose. 
The following steps need to be done:
- [x] Add mallet to URDF (see #44 )
- [x] Add constraints for the wrist height and position to get a good hitting motion
- [x]  Solve this new configuration with the bio_ik in the same way as now

**Comment by berkgungor** [comment]
all looks done
