### ISSUE TITLE
Create use negative data for vision

### ISSUE THREAD

**Issue by Flova** [UHHRobotics22-23/MarimbaBot#66]
Create a negative dataset for the vision that includes:
- Random coco images
- Blank note sheets

**Comment by yunlong-wang-cn** [comment]
The creation of the whiteboard dataset is done, you can find (here)[https://cloud.mafiasi.de/s/P5nWneNGbRzscd2].

**Comment by yunlong-wang-cn** [comment]
Since the rest will done by Florian we both decide to close this issue.

**Comment by Flova** [comment]
Reopening because I still need to train the model with the new data
