### ISSUE TITLE
Add sharp notes etc. to vision dataset

### ISSUE THREAD

**Issue by Flova** [UHHRobotics22-23/marimbabot#70]
Add more special characters to the vision dataset
- [x] #101
- [x] collect them irl

**Comment by Flova** [comment]
Subtask of #43

**Comment by scaredycode** [comment]
also consider:
prelude, repeat signs

**Comment by Juphex** [comment]
https://github.com/UHHRobotics22-23/marimbabot/issues/70#issuecomment-1534731239
