### ISSUE TITLE
add tempo to notes message

### ISSUE THREAD

**Issue by scaredycode** [UHHRobotics22-23/marimbabot#92]
add the speed (bpm) the note sequence is to be played to the message

**Comment by Flova** [comment]
At what point in the pipeline?

**Comment by Juphex** [comment]
I am not quite sure but isn't this what you/we are looking for?  https://lilypond.org/doc/v2.23/Documentation/notation/displaying-rhythms#metronome-marks 

I am not sure wheter tempo can be interpreted as Beats Per Minute

**Comment by Juphex** [comment]
And btw. this may also what you would like to use inside the behaviour, isnt it? https://lilypond.org/doc/v2.23/Documentation/music-glossary/tempo-indication

**Comment by scaredycode** [comment]
> At what point in the pipeline?

I would always assign a default tempo in the behavior node which I would add to the message for the read_notes / play_notes topic.
In case of "faster" / "slower" commands this default tempo would then be increased/decreased by some predefined value, or the tempo could be specified by a direct "play it as 120 bpm" command (example). 
We could also try to train the vision to recognize drawn tempo indications and add that to the recognized_notes topic direcrly.
![Screen-Shot-2015-06-23-at-3.03.20-PM-1.png](https://user-images.githubusercontent.com/57991801/236291490-0a98692a-c4fc-4278-97e8-df716faf15b3.png)

**Comment by scaredycode** [comment]
> I am not quite sure but isn't this what you/we are looking for?  https://lilypond.org/doc/v2.23/Documentation/notation/displaying-rhythms#metronome-marks 
> 
> I am not sure wheter tempo can be interpreted as Beats Per Minute

Yes this is exactly what I had in mind, although I was not sure how to include it in the current message format as we only use the Note sequence as a string. We could either just add the "\tempo 4=100" part at the beginning of the string, or we could add a separate field type specifcally for the tempo for easier access.

Also to answer your question: tempo can be direcrly translated to bpm. 4=100 or quarter note=100 basically means 100 quarter notes or beats per minute. (see Image in previous comment)
A tempo indication as Text ("adagio", "allegretto", "allegro",... ) can be translated to a bpm range. In that case we can just assign one bpm value whithin the range to each recognized marking.

**Comment by Juphex** [comment]
Thanks, I will keep this in mind in https://github.com/UHHRobotics22-23/marimbabot/pull/90

**Comment by Juphex** [comment]
@scaredycode what is the status of this issue? Is this tackled by the part you are currently working on? :)
