### ISSUE TITLE
failure at requirement.txt

### ISSUE THREAD

**Issue by yunlong-wang-cn** [UHHRobotics22-23/marimbabot#93]
### Building wheel for mycroft-mimic3-tts (setup.py) ... error

The content in the requirements.txt:

abjad==3.4
albumentations==1.3.0
nltk==3.7
numpy==1.23.3
opencv-python==4.7.0.68
Pillow==9.4.0
pytorch_lightning==1.8.1
torch==1.13.1
tqdm==4.64.0
transformers[sentencepiece]==4.26.0
mycroft-mimic3-tts==0.2.4

**Comment by yunlong-wang-cn** [comment]
Since the version of each package in the `requirement.txt` is specified, therefore it is pretty hard to avoid incompatibility.

**Comment by yunlong-wang-cn** [comment]
if I try to manually install the mycroft-mimic3-tts, I encounter this error:
`ERROR: scikit-image 0.20.0 has requirement scipy<1.9.2,>=1.8; python_version <= "3.9", but you'll have scipy 1.10.1 which is incompatible.`

**Comment by Flova** [comment]
It seem to be related to the changes in #17
